# services:
#   mongodb

sudo: required

services:
  - xvfb

addons:
  firefox: "latest"

before_script:
  - export DISPLAY=:99.0
  - sleep 5
  - npm run build &
  - npm run server &
  - sleep 5
  - firefox http://localhost:5777/utest/ &
  - sleep 8
 
script:
  - "npm test"
 
language: node_js


node_js:
  - "10.1.0"