services:
  mongodb

sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - node_modules/.bin/atma &
  - node_modules/.bin/atma server &
  - sleep 5
  - firefox http://localhost:5777/utest/ &
  - sleep 8
 
script:
  - "npm test"
 
language: node_js
node_js:
  - "5.6.0"
compiler: clang-3.4
env:
  - CXX=clang-3.4
